
services:
  # User Service
  user-service:
    build: ./services/user
    ports:
      - "8000:8000"
    depends_on:
      - user-db
      - redis
    volumes:
      - ./services/user/app:/app
    environment:
      - ./services/user/app/.env

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"  

  user-db:
    image: postgres:17
    restart: always 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: healing_user
    ports:
      - "5433:5432"
    env_file:
      - ./services/user/app/.env  
    volumes:
      - user_pgdata:/var/lib/postgresql/data


  gateway:
    image: nginx:alpine
    container_name: api-gateway
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - user-service

  # Consultation Service
  # consultation-service:
  #   build: ./services/consultation
  #   ports:
  #     - "8001:8001"
  #   depends_on:
  #     - consultation-db
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:root@consultation-db:5432/healing_consultation

  # consultation-db:
  #   image: postgres:17
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: healing_consultation
  #   ports:
  #     - "5434:5432"
  #   volumes:
  #     - consultation_pgdata:/var/lib/postgresql/data

  # # Payment Service
  # payment-service:
  #   build: ./services/payment
  #   ports:
  #     - "8002:8002"
  #   depends_on:
  #     - payment-db
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:root@payment-db:5432/healing_payment

  # payment-db:
  #   image: postgres:17
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: healing_payment
  #   ports:
  #     - "5435:5432"
  #   volumes:
  #     - payment_pgdata:/var/lib/postgresql/data

  # Frontend
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:5173"
  #   stdin_open: true
  #   tty: true

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  
    ports:
      - "5173:5173"
    command: yarn dev 

volumes:
  user_pgdata:
  consultation_pgdata:
  payment_pgdata:
