"""add is_available in psychiatrics_profile table

Revision ID: 22b1450baef5
Revises: 9d0b8a042273
Create Date: 2025-05-27 09:51:23.860446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b1450baef5'
down_revision: Union[str, None] = '9d0b8a042273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psychologist_profile', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psychologist_profile', 'is_available')
    # ### end Alembic commands ###
