"""update psychiatrics_profile table 1

Revision ID: 68e03f245937
Revises: 8ed27bb10937
Create Date: 2025-07-04 07:04:09.018989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e03f245937'
down_revision: Union[str, None] = '8ed27bb10937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psychologist_profile', sa.Column('reason_block', sa.Text(), nullable=True))
    op.alter_column('psychologist_profile', 'is_verified',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('psychologist_profile', 'is_verified',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)
    op.drop_column('psychologist_profile', 'reason_block')
    # ### end Alembic commands ###
