"""default value for update

Revision ID: c513925e6db8
Revises: a906a9711a57
Create Date: 2025-07-03 09:31:36.238529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c513925e6db8'
down_revision: Union[str, None] = 'a906a9711a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('psychologist_profile', 'is_verified',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('psychologist_profile', 'is_verified',
               existing_type=sa.String(length=25),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
