"""adding the sender field to table chat

Revision ID: 136d568f42ff
Revises: b95e97ddabca
Create Date: 2025-06-14 15:18:14.500919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136d568f42ff'
down_revision: Union[str, None] = 'b95e97ddabca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('sender', sa.Text(), nullable=False))
    op.add_column('chat', sa.Column('consultation_map_id', sa.Integer(), nullable=True))
    op.drop_constraint('chat_consultation_id_fkey', 'chat', type_='foreignkey')
    op.create_foreign_key(None, 'chat', 'consultation_mapping', ['consultation_map_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat', 'consultation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('consultation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.create_foreign_key('chat_consultation_id_fkey', 'chat', 'consultation_mapping', ['consultation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat', 'consultation_map_id')
    op.drop_column('chat', 'sender')
    # ### end Alembic commands ###
