"""changing the unique fields

Revision ID: 23538e70f30c
Revises: 814e6a42f68e
Create Date: 2025-06-11 06:24:41.959385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23538e70f30c'
down_revision: Union[str, None] = '814e6a42f68e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_consultation_mapping_psychologist_id', table_name='consultation_mapping')
    op.create_index(op.f('ix_consultation_mapping_psychologist_id'), 'consultation_mapping', ['psychologist_id'], unique=False)
    op.drop_index('ix_consultation_mapping_user_id', table_name='consultation_mapping')
    op.create_index(op.f('ix_consultation_mapping_user_id'), 'consultation_mapping', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultation_mapping_user_id'), table_name='consultation_mapping')
    op.create_index('ix_consultation_mapping_user_id', 'consultation_mapping', ['user_id'], unique=True)
    op.drop_index(op.f('ix_consultation_mapping_psychologist_id'), table_name='consultation_mapping')
    op.create_index('ix_consultation_mapping_psychologist_id', 'consultation_mapping', ['psychologist_id'], unique=True)
    # ### end Alembic commands ###
