"""adding chat attachment file and changes in chat model

Revision ID: 2f33ae0250c6
Revises: 53400d079df1
Create Date: 2025-06-25 15:33:55.330533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f33ae0250c6'
down_revision: Union[str, None] = '53400d079df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_type', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('upload_status', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_attachments_id'), 'chat_attachments', ['id'], unique=False)
    op.add_column('chat', sa.Column('message_type', sa.Text(), nullable=True))
    op.add_column('chat', sa.Column('has_attachments', sa.Boolean(), nullable=True))
    op.alter_column('chat', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('chat', 'has_attachments')
    op.drop_column('chat', 'message_type')
    op.drop_index(op.f('ix_chat_attachments_id'), table_name='chat_attachments')
    op.drop_table('chat_attachments')
    # ### end Alembic commands ###
