"""changing the unique constraints

Revision ID: 67f81892953b
Revises: f11a457d02be
Create Date: 2025-06-05 13:22:33.370935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f81892953b'
down_revision: Union[str, None] = 'f11a457d02be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_consultation_psychologist_id', table_name='consultation')
    op.create_index(op.f('ix_consultation_psychologist_id'), 'consultation', ['psychologist_id'], unique=False)
    op.drop_index('ix_consultation_user_id', table_name='consultation')
    op.create_index(op.f('ix_consultation_user_id'), 'consultation', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultation_user_id'), table_name='consultation')
    op.create_index('ix_consultation_user_id', 'consultation', ['user_id'], unique=True)
    op.drop_index(op.f('ix_consultation_psychologist_id'), table_name='consultation')
    op.create_index('ix_consultation_psychologist_id', 'consultation', ['psychologist_id'], unique=True)
    # ### end Alembic commands ###
