"""video field in compliant

Revision ID: 77959cc25006
Revises: 2f33ae0250c6
Create Date: 2025-06-30 04:53:57.615196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77959cc25006'
down_revision: Union[str, None] = '2f33ae0250c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint', sa.Column('video', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaint', 'video')
    # ### end Alembic commands ###
