"""adding the table consult mapping

Revision ID: 814e6a42f68e
Revises: 67f81892953b
Create Date: 2025-06-11 06:21:39.861892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '814e6a42f68e'
down_revision: Union[str, None] = '67f81892953b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('psychologist_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_mapping_id'), 'consultation_mapping', ['id'], unique=False)
    op.create_index(op.f('ix_consultation_mapping_psychologist_id'), 'consultation_mapping', ['psychologist_id'], unique=True)
    op.create_index(op.f('ix_consultation_mapping_user_id'), 'consultation_mapping', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultation_mapping_user_id'), table_name='consultation_mapping')
    op.drop_index(op.f('ix_consultation_mapping_psychologist_id'), table_name='consultation_mapping')
    op.drop_index(op.f('ix_consultation_mapping_id'), table_name='consultation_mapping')
    op.drop_table('consultation_mapping')
    # ### end Alembic commands ###
