"""adding duration field in the consultation table

Revision ID: a893f38c9ac2
Revises: 45cc57839a20
Create Date: 2025-06-19 05:08:32.411199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a893f38c9ac2'
down_revision: Union[str, None] = '45cc57839a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultation', sa.Column('duration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultation', 'duration')
    # ### end Alembic commands ###
