"""update consultaion and complaint

Revision ID: d720cd98dce4
Revises: 77959cc25006
Create Date: 2025-07-06 15:50:08.772426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd720cd98dce4'
down_revision: Union[str, None] = '77959cc25006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaint', 'video')
    op.add_column('consultation', sa.Column('video', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultation', 'video')
    op.add_column('complaint', sa.Column('video', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
