"""update wallet and transactions with created at

Revision ID: f9c62ddbd89c
Revises: 25abf0729b6b
Create Date: 2025-08-09 04:25:01.019277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c62ddbd89c'
down_revision: Union[str, None] = '25abf0729b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('wallet_transaction', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_transaction', 'created_at')
    op.drop_column('wallet', 'created_at')
    # ### end Alembic commands ###
